/** Pares from→to alineados con `prisma/seed.ts` (workflow predeterminado). */
export const DEFAULT_WORKFLOW_TRANSITION_PAIRS: ReadonlyArray<readonly [string, string]> = [
  ['abierto', 'triaje'],
  ['abierto', 'asignado'],
  ['abierto', 'en_progreso'],
  ['triaje', 'abierto'],
  ['triaje', 'asignado'],
  ['asignado', 'abierto'],
  ['asignado', 'en_progreso'],
  ['asignado', 'resuelto'],
  ['en_progreso', 'asignado'],
  ['en_progreso', 'resuelto'],
  ['en_progreso', 'abierto'],
  ['en_progreso', 'pendiente_repuestos'],
  ['pendiente_repuestos', 'en_progreso'],
  ['asignado', 'pendiente_repuestos'],
  ['pendiente_repuestos', 'asignado'],
  ['pendiente_repuestos', 'resuelto'],
  ['pendiente_repuestos', 'cerrado'],
  ['resuelto', 'en_progreso'],
  ['resuelto', 'cerrado'],
  ['en_progreso', 'cerrado'],
  ['asignado', 'cerrado'],
  ['triaje', 'cerrado'],
  ['abierto', 'cerrado'],
  ['abierto', 'cancelado'],
  ['triaje', 'cancelado'],
  ['asignado', 'cancelado'],
  ['en_progreso', 'cancelado'],
  ['pendiente_repuestos', 'cancelado'],
  ['resuelto', 'cancelado'],
];
